PAPP-23589 - Add md5 support for generating SDI for non-fips Phantom …
splunk-soar-connectors/office365 pull request #11
Opened 2022-01-14 00:42 UTC by chunmanjimmyf

…instances

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [X] Testing of all the changes has been performed (for bug fixes / features)
- [X] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [X] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [X] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [X] Verify all checks are passing.
- [X] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [X] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Currently we generate SDIs in SHA256 format when creating artifacts on ingestion.

## What is the new behavior? (OPTIONAL)
- For non-fips Phantom instances, we will generate SDIs in MD5 format so we do not create duplicate artifacts if the artifact already existed prior.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2022-01-18 10:24 UTC, chunmanjimmyf commented
Integration Test Failure: trace_email_valid is new & requires https://github.com/splunk-soar-connectors/office365/pull/3 to be merged in. All other tests are passing.

2022-01-18 20:12 UTC, alexa-phantom requested changes

2022-01-18 20:12 UTC, alexa-phantom commented on ewsonprem_connector.py
> +        if (fips_enabled):
Don't need parenthesis

2022-01-19 00:44 UTC, chunmanjimmyf commented on ewsonprem_connector.py
> +        if (fips_enabled):
Updated.

2022-01-19 00:57 UTC, rgil-splunk approved these changes

2022-01-19 01:10 UTC, ricardo-phantom approved these changes

2022-01-19 08:48 UTC, chunmanjimmyf commented
Closed in favour of https://github.com/splunk-soar-connectors/office365/pull/13 due to merge conflicts.

2022-01-19 08:48 UTC, closed without merging